spring.application.name=SecurityFinalRound

spring.datasource.url=jdbc:mysql://localhost:3306/securityDB
spring.datasource.username=root
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.security.key=championtheonetheonlypoundforpoundnumberonejonbonesjones